### ISSUE TITLE
Publish / unpublish object and its children

### ISSUE THREAD

**Issue by coblej** [duke-libraries/ddr-models#126]
Add functionality when publishing / unpublishing an object to optionally publish / unpublish its children and their children.

**Comment by coblej** [comment]
@jt112 @dchandekstark To do this, I think we need some clarification on the desired functionality, which may not be exactly what is specified in the comment above.  Assuming that publication (or non-publication) is handled primarily at the collection level and downwards ...
- If I publish a collection, does it automatically publish all items and components in that collection?
- If I add an item / component to a published collection, is it automatically published?
- If I have a published collection, can some items / components be unpublished?
- If items / components in a published collection can have an unpublished status, what does that look like to the (staff) user?  How do they publish unpublished items / components in a published collection?  How do they unpublish published items / components in a published collection?
- What user role(s) should be allowed to publish / unpublish collections?
- I assume that it doesn't make sense to have a published item in an unpublished collection nor a published component in an unpublished item.  If that assumption is incorrect, we need to clarify what that means.

**Comment by dchandekstark** [comment]
Fixed in 3.0 at least.
