### ISSUE TITLE
HasChildren first_child should use structMetadata 'order' attribute

### ISSUE THREAD

**Issue by coblej** [duke-libraries/ddr-models#154]
if available, else fall back to sorting by (first) identifier

**Comment by dchandekstark** [comment]
@coblej Is this still relevant?

**Comment by coblej** [comment]
@dchandekstark Well, yes and no.  Yes, in that we should take structural metadata into account when identifying the "first child" of an object.  No, in that the mechanism for doing would be a bit different now.

**Comment by dchandekstark** [comment]
@coblej So, are we still pinning to 2.0.0?

**Comment by coblej** [comment]
@dchandekstark I would say no and have correspondingly unpinned it.

**Comment by coblej** [comment]
Addressed in 8ac565df9521274f765133c257d15914f7c58bd0 in fcrepo4 branch.
