### ISSUE TITLE
Ddr::Models::HasChildren#first_child errors if no children

### ISSUE THREAD

**Issue by coblej** [duke-libraries/ddr-models#165]
In pre-structural metadata versions of ddr-models, sort by pid (document id) if no identifiers.

For post-structural metadata versions of dd-rmodels, use structural metadata order attribute.

**Comment by dchandekstark** [comment]
I don't see that -- I guess we need test coverage. :)

I do see that #first_child will error if no children b/c calling .first["id"] on empty array.
