### ISSUE TITLE
Add "owner" attribute for items in digital collections.

### ISSUE THREAD

**Issue by willsexton** [duke-libraries/ddr-models#171]
Objects in digital collections are typically associated with an administrative entity. This entity, usually a department in the library, "owns" the object, either in terms of providing curatorial and administrative control over the original item, or simply by providing support for researchers inquiring about it. Contact information about the "owner" appears in the "Research Help" area of an item's page layout; [here's an example](http://library.duke.edu/digitalcollections/gamble_244-1373/).

[Here's the owners.py file from Tripod2](https://github.com/duke-libraries/tripod2-django/blob/master/local/owners.py), to show the data we currently use and the slugs we use for identifying the different administrative entities.

**Comment by dchandekstark** [comment]
I would like to discuss this in the context of the new roles framework.

**Comment by coblej** [comment]
@dchandekstark Yes, we should talk about it.  I think the intent here is conceptually different from the "owner" role we've been discussing vis-a-vis access controls.

**Comment by dchandekstark** [comment]
@coblej FWIW it doesn't sound different to me ("providing curatorial and administrative control over the original item") and if it is different, we should resolve the differences or use a different term for one of the use cases.

**Comment by coblej** [comment]
@dchandekstark Yeah, bad choice of words on my part.  Not really "conceptually different".  Just not sure how they fit together implementation-wise.

**Comment by dchandekstark** [comment]
@willsexton One thing to discuss is an RDF representation of this type of entity.  At a glance it looks as if FOAF and/or vCard provides most of what is needed.

Just to put some thoughts down here:

RDF type - foaf:Organization / vcard:Organization
name - foaf:name / vcard:organization-name
url - foaf:homepage / vcard:hasURL
phone - foaf:phone / vcard:hasTelephone
email - vcard:hasEmail

Not sure about the slug - could use vcard:nickname ?
"ask" might be a custom term?

**Comment by willsexton** [comment]
In this case, the entity is going to be an organization and not an individual. There's also no intent to imply curatorial or administrative control of the digital object within the repository. The primary purpose is to show intellectual custody of the object for a researcher. It's the answer to the question, "Whom do I ask about this item?"

**Comment by dchandekstark** [comment]
OK, so we need to disambiguate this "owner" from an "owner" access role in the repository, if we actually need the latter.

**Comment by dchandekstark** [comment]
@jt112 @willsexton @coblej I think duke-libraries/dul-hydra/#587 is at least an overlapping concern.  Can we reconcile them or do we need two different things here?  Sounds like, for the DDR, we're talking about contact information and not (necessarily) access control.

**Comment by willsexton** [comment]
I do see overlap in your discussion of https://github.com/duke-libraries/dul-hydra/issues/587. I wonder if the "owner" that I'm describing can serve as a Role in your model. Calling it "owner" implies a level of access control beyond what I've described (which is, in fact, no access control). So maybe it makes sense to rename it to "reference"?

I like the FOAF/vCard model for representing the data for an organization.

Finally, I think it makes sense to assign this value to a collection, and allow the members of the collection to inherit it, but also to be able to override that assignment at the item level.

**Comment by dchandekstark** [comment]
I like the "reference" idea (or maybe "contact"?).  I'm leaning now towards this *not* being a role, for three reasons: there are no associated permissions, the "agent" is different from a role agent (which is a user or group), and the inheritance you describe is different from role "inheritance".

**Comment by dchandekstark** [comment]
I'm now thinking FWIW of using http://schema.org/ContactPoint for this metadata.

**Comment by jt112** [comment]
I like it!



On Apr 13, 2015, at 06:52, David Chandek-Stark <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm now thinking FWIW of using http://schema.org/ContactPoint for this metadata.

-

**Comment by dchandekstark** [comment]
@willsexton  Is it possible to repurpose web pages like this: http://library.duke.edu/rubenstein/bingham/contact ?

**Comment by willsexton** [comment]
We currently link to the home page for the center (<http://library.duke.edu/rubenstein/bingham/>), and I think that would probably be preferable for the default URL.

**Comment by dchandekstark** [comment]
@willsexton Sorry, what I meant was that the information on that page duplicates the information we would be presenting.  I suppose, however, that it's not in a structured format that could be reused.

**Comment by dchandekstark** [comment]
@coblej I removed the NESCent milestone b/c I think admin_set covers what is needed for those collections.

**Comment by dchandekstark** [comment]
@willsexton Has this need been met by "contact" info? @seanaery @corylown

**Comment by dchandekstark** [comment]
@willsexton @jt112 Please create a story in Jira if this is still relevant.
