### ISSUE TITLE
Add indexed administrative metadata field for display format

### ISSUE THREAD

**Issue by willsexton** [duke-libraries/ddr-models#172]
I will document this one on Basecamp, include the link here.

**Comment by willsexton** [comment]
The current platform for digital collections, Tripod2, supports 14 different content types for display. It also uses hooks to render page templates for items at different levels of granularity, which I'll explain further down.

The goal of this enhancement is to emulate this functionality. The outcome should be a scheme whereby, given an item of a particular type in a particular collection, a designer can know what to name a template file and where to save it.

With Tripod2, the content type is determined when the METS files are generated, and specified in the TYPE attribute of the <mets> root node. Example: `<mets ID="vica_viccb01001" TYPE="Resource:slideshow">`

With the new application, I'm suggesting implementing an algorithm that will inspect the Components associated with an Item, test for their media types, look at other structural metadata elements that may be present, and make a conclusion about the content type. Then it will index that value in Blacklight/SOLR to be retrieved by the application layer. That value will be keyed to a pattern for naming and organizing of templates. There may be a better approach than what I'm suggesting; I'm not familiar enough with Blacklight/Hydra/Rails to say. 

For now, we have two content types to work with: image (single-image types), and what we call "slideshow" in Tripod2 (multi-image types, though we can think of a better name). For the former, we have the Blake collection, for the latter, Vica.

Looking at items from these two collections in the staff interface, I think we can use the following rules:

* Image - Item consists of a single Component, with Media Type  = image/tiff
* Multi-image - Item consists of multiple Components, all of which are Media Type = image/tiff

This logic may work for now, but there may be further assumptions that come into play that require us to think about enhancing the component-level metadata and providing structural metadata. Whatever scheme we use to handle this logic should be extensible, as we'll need to incorporate about a dozen more content types.

Finally (and maybe this should be a separate issue), we need a scheme for keying content types to layouts. As I mentioned, there are hooks in Tripod2 to enable levels of precedence for templates, based on content type and collection.

* By item identifier - We may never have implemented this one, but it's an available hook. If a template named [collectionid]/templates/[itemid].html exists, use it.
* By type of item in a collection - For example, Gamble photographs are multi-image items ("slideshow" in Tripod2), but a gamble/templates/slideshow.html template handles them, to display the photograph and the scanned label together.
* Generically by item type - The vast majority of cases are handled by generic templates for the content type (e.g., templates/slideshow.html)

**Comment by willsexton** [comment]
Here's some more discussion of this task on Basecamp: https://basecamp.com/2517156/projects/8203819/messages/40213354

**Comment by dchandekstark** [comment]
@willsexton @corylown @seanaery @coblej After the scrum today there seemed to be agreement that we needed to separate two different concepts -- what a thing *is* (its "type") vs. how it is to be *displayed* ("format"?).  My takeaway is that it is useful to record in the repository the *type* -- e.g., photograph, card, book, poster, etc.  Perhaps in many cases this information in combination with other aspects of the record can determine the display (slideshow, carousel, page-turner).  Since the descriptive metadata field dcterms:type is already overloaded in many cases, and we need a single value for the repository object "type", I proposed adding a dcterms:type field to the administrative metadata for this purpose. (We can call it resource_type if you like.)  In cases where we want to customize the display for a particular collection or item, we may be able to simply use a custom template/partial.  If not, we can revisit adding a "display_format" field to administrative metadata for manually specifying the value.

**Comment by willsexton** [comment]
Following up on our discussion in the Tripod3 standing meeting yesterday - we decided to use a "model" attribute tied to a "display" namespace mapped to http://repository.lib.duke.edu/vocab/display. The attribute will be provided by the METS file for an object used either when an object is updated from METS (i.e., with descriptive metadata), or later, at the time of ingest. That value is currently stored in the TYPE attribute of the root node of the METS file, and has the pattern TYPE="Resource:<model>" for item-level objects, where model is some value such as "slideshow" (currently, but will change to something else) or "image" or "video". 

Thus we can expect the ddr-models API to provide a method or an attribute for an object called "display_model" that will return this value.

**Comment by coblej** [comment]
@willsexton @dchandekstark In the comment directly above, it is noted that a decision was made to call the attribute "model" (in a "display" vocabulary namespace) and to provide a "display_model" API method  to return the value.  Just double-checking that this is really what we want (as opposed to "format" and "display_format").

**Comment by coblej** [comment]
@willsexton @dchandekstark In today's stand-up meeting, we decided to use the property name "format" and the API method "display_format" rather than "model" and "display_model".
