### ISSUE TITLE
Refactor external file store configuration

### ISSUE THREAD

**Issue by coblej** [duke-libraries/ddr-models#175]
Rather than using single environment variables like EXTERNAL_FILE_STORE and PTIF_EXTERNAL_FILE_STORE, configure external file stores using a hash where the keys are datastream ID's (and a default one) and the values are a hash of attributes such as external file store path, subpath pattern, and (applicable to generated derivatives) extension to use in external file name.

**Comment by dchandekstark** [comment]
@coblej I think perhaps this is not relevant in FCR4?

**Comment by coblej** [comment]
@dchandekstark We are still using PTIF_EXTERNAL_FILE_STORE in FCR4 versions of our code, since we're still generating and storing PTIF derivatives ... though not as external datastreams, of course.
