### ISSUE TITLE
FileManagement#add_file sets file name as datastream label

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/ddr-models#276]
e.g., `RackMultipart20150710-10345-e124lh`

**Comment by dchandekstark** [comment]
@coblej This is happening b/c we use AF's `add_file_datastream`. I am inclined to "fix" it, even though it's not a technical problem, because it's junk data and not useful preservation information.  We could either set the label explicitly to the standard content datastream label, or use the original file name, or something else (possibly user-entered). Thoughts?

**Comment by coblej** [comment]
@dchandekstark I suggest setting the label to the standard content datastream label, which according to Ddr::Models::HasContent is 'Content file for this object'.

**Comment by dchandekstark** [comment]
@coblej OK, in that case, we should probably use the ds_spec to get the value. Cf. #275

**Comment by dchandekstark** [comment]
Specifically, file name is used as a default label in `create_datastream`: https://github.com/projecthydra/active_fedora/blob/v7.1.2/lib/active_fedora/datastreams.rb#L151-L153.

**Comment by dchandekstark** [comment]
Ultimately, this effect is due to an inconsistency in the way AF 7 creates datastreams.  Although our models define the default label for the "content" datastream, the `create_datastream` method used via `add_file_datastream` only uses the default attributes of the datastream *class* -- i.e. `ActiveFedora::Datastream`.  Therefore, I think the way to achieve the desired result without either duplicating the default label or monkey-patching AF is to define a `ContentFileDatastream` class.

**Comment by dchandekstark** [comment]
My comment above is not entirely correct. I see now that `add_file_datastream` *only* respects and explicitly passed `:label` option; otherwise it uses the file name as the label.  Neither the ds spec nor the ds class default attributes matter.

**Comment by dchandekstark** [comment]
Provisional decision is to not fix the behavior, but rather to deal with it in F4 migration, assuming that there's even a place for the F3 datastream label to go.
