### ISSUE TITLE
Virus scan failures in derivatives generation

### ISSUE THREAD

**Issue by coblej** [duke-libraries/ddr-models#289]
Adding a generated derivative to an object generates a virus scan failure on the derivative file ... e.g., `/tmp/d20150715-1475-ulzhh2/output.out: lstat() failed: Permission denied. ERROR (ClamAV 0.98.7/20695/Tue Jul 14 20:50:12 2015)`

**Comment by dchandekstark** [comment]
Should be fixed via 886c766ee7becb9be4c6078ef51c159f32e58491.
