### ISSUE TITLE
Copy date to a facet field in Solr index

### ISSUE THREAD

**Issue by corylown** [duke-libraries/ddr-models#336]
The Duke & Sons collection items have a date field with values such as date: ["1886; 1887; 1888; 1889; 1890"]. We'd like to be able to provide faceted access to this field. Each year should be stored as a separate value in the new facet field (i.e, split at ';\s').

**Comment by dchandekstark** [comment]
This creates an interesting challenge across the repository as a whole, since the date field (dcterms:date I assume) is not controlled.  Is this a case for, so to speak, a "collection-specific" facet?  

/cc @coblej

**Comment by coblej** [comment]
@corylown @dchandekstark For me, this request raises several issues deserving consideration.  (1) This date metadata is currently stored in a single dcterms:date field as the single string shown above.  I think a better representation of repeated fields would be multiple dcterms:date fields, each containing one of the repeated values.  This is something we can fix post-facto in the case of this particular collection but which I think would be better fixed pre-facto (if there is such a word) before the metadata is added to the object in the repository.  (2) I think the ability to facet on date will be a common use case in the repository but handling dates in Solr is not particularly straightforward and we should be thoughtful in how we go about that.  A good topic for some discussion.

**Comment by coblej** [comment]
@dchandekstark In terms of a "collection-specific" facet, I can imagine cases where we may want to display certain facets for some collections but not for others.  That said, I imagine date will be a fairly frequent useful facet so I'm hoping we can do something about date faceting that is general enough that it doesn't apply to just this one collection.

**Comment by dchandekstark** [comment]
@coblej Yeah, I'm just not how sure useful a repository-wide date facet would be at this point due to the lack of control.

**Comment by corylown** [comment]
@dchandekstark @coblej this sounds like a topic for discussion at our Tripod3 meeting on Monday (August 17) if you can both attend. Will should be back from vacation then and he may be able to provide more information about how dates are stored and used in other digital collections.

I think there will be other cases where a facet field is useful only for particular collections. Developing a strategy for handling these cases would be useful.

**Comment by dchandekstark** [comment]
@coblej Part of this discussion might be about whether to simply change the current index field to store the data as "string" rather than "text" (tokenized).  I think it depends on what the date-related discovery stories are.
