### ISSUE TITLE
Create year facet field based on dcterms:date

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/ddr-models#340]
For use with blacklight_range_limit plugin: index each discernable year as an integer.

/cc @corylown @seanaery 

Cf. #336

**Comment by dchandekstark** [comment]
- Split value on /\s*;\s*/ and strip
Each:
- DateTime.parse - if parseable, get year to_i and done
- /\d{4}-\d{4}/ - to array of int
- /\d{4}-\d{2}/ - treat first num as year
- /\d4/

**Comment by seanaery** [comment]
I took a trip through the Date facet browse pages in Tripod2 (e.g., http://library.duke.edu/digitalcollections/eaa/Date/ generated via the METS files). Beyond the patterns we discussed, here are actual examples of anomalous date values. Some are obviously errors in need of correction:

1539
21-Apr-72
18510515
18550727
18550927
18610101
[186-?] 
[186-] 
[187x] 
[1880s] 
[1929-1964] 
[1941 Feb. 20?] 
[19xx] 
[between 1540-1550?]
[between 1550 and 1586?]
[between 1854 and 1859] 
[ca. 1880s-1890s] 
[ca. 1881] 
[ca. 1890s] 
[ca. 1931 Dec. 10] 
[ca. late 1880s] 
[post 1915] 
0187-10-03 
0187-11-17 
0191-06-05 
1750-1800 
1861, 1864 
1898-08-1d9dd 
1916 [Dec. 20?] 
1918/1919 
1918/1921 
1931 Apr. 18 
1933 May 22 
1935 March 
194? 
1940s? 
1943/1945 
1949-07-02,1949-07-02 
194X 
194x 
195? 
1953 [Nov.-Dec.] 
1959 Sep 11 
1959-10-14, 1959-10-21 
1959; 1960; 1961; 1962; 1963; 1964; 1965; 1966; 1967 
195x 
1963/04 
1963/12 
1963/13 
1964/02 
1964/07 
1979 Apr. 17-23 
1979 of 1980 
1979 or 1980 
1982-ca. 1983 
2016-03 
Between 1965 and 1968 
c.1905 
c1918, c1912 
c1920 
circa 1910s-1920s 
Feb. 1968 - Aug. 1969 
n.d 
None 
unkn

**Comment by dchandekstark** [comment]
Running the values through `Date.parse` gives some interesting results - some expected failures, of course.

```
Date: 1539
NOT PARSEABLE

Date: 21-Apr-72
Year: 1972

Date: 18510515
Year: 1851

Date: 18550727
Year: 1855

Date: 18550927
Year: 1855

Date: 18610101
Year: 1861

Date: [186-?]
Year: 2015

Date: [186-]
Year: 2015

Date: [187x]
Year: 2015

Date: [1880s]
NOT PARSEABLE

Date: [1929-1964]
NOT PARSEABLE

Date: [1941 Feb. 20?]
Year: 1941

Date: [19xx]
Year: 2015

Date: [between 1540-1550?]
NOT PARSEABLE

Date: [between 1550 and 1586?]
NOT PARSEABLE

Date: [between 1854 and 1859]
NOT PARSEABLE

Date: [ca. 1880s-1890s]
NOT PARSEABLE

Date: [ca. 1881]
NOT PARSEABLE

Date: [ca. 1890s]
NOT PARSEABLE

Date: [ca. 1931 Dec. 10]
Year: 1931

Date: [ca. late 1880s]
NOT PARSEABLE

Date: [post 1915]
NOT PARSEABLE

Date: 0187-10-03
Year: 187

Date: 0187-11-17
Year: 187

Date: 0191-06-05
Year: 191

Date: 1750-1800
NOT PARSEABLE

Date: 1861, 1864
NOT PARSEABLE

Date: 1898-08-1d9dd
Year: 1898

Date: 1916 [Dec. 20?]
Year: 2015

Date: 1918/1919
NOT PARSEABLE

Date: 1918/1921
NOT PARSEABLE

Date: 1931 Apr. 18
Year: 1931

Date: 1933 May 22
Year: 1933

Date: 1935 March
Year: 1935

Date: 194?
Year: 2015

Date: 1940s?
NOT PARSEABLE

Date: 1943/1945
NOT PARSEABLE

Date: 1949-07-02,1949-07-02
Year: 1949

Date: 194X
Year: 2015

Date: 194x
Year: 2015

Date: 195?
Year: 2015

Date: 1953 [Nov.-Dec.]
Year: 2015

Date: 1959 Sep 11
Year: 1959

Date: 1959-10-14, 1959-10-21
Year: 1959

Date: 1959; 1960; 1961; 1962; 1963; 1964; 1965; 1966; 1967
NOT PARSEABLE

Date: 195x
Year: 2015

Date: 1963/04
Year: 1963

Date: 1963/12
Year: 1963

Date: 1963/13
NOT PARSEABLE

Date: 1964/02
Year: 1964

Date: 1964/07
Year: 1964

Date: 1979 Apr. 17-23
Year: 1979

Date: 1979 of 1980
NOT PARSEABLE

Date: 1979 or 1980
NOT PARSEABLE

Date: 1982-ca. 1983
NOT PARSEABLE

Date: 2016-03
NOT PARSEABLE

Date: Between 1965 and 1968
NOT PARSEABLE

Date: c.1905
NOT PARSEABLE

Date: c1918, c1912
NOT PARSEABLE

Date: c1920
NOT PARSEABLE

Date: circa 1910s-1920s
NOT PARSEABLE

Date: Feb. 1968 - Aug. 1969
Year: 1968

Date: n.d
NOT PARSEABLE

Date: None
NOT PARSEABLE

Date: unkn
NOT PARSEABLE
```
