### ISSUE TITLE
Mechanism for associating text of deposit agreement with object

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/ddr-models#353]

**Comment by dchandekstark** [comment]
@coblej Assuming that the deposit agreement is represented by another object in the repository (containing the text of the agreement), the most straightforward approach in Fedora 3 is to use RELS-EXT.  Setting the object of an RDF statement (say, in adminMetadata) to the uri of another repository object does not (in AF 7) work to automatically retrieve the referenced object.

**Comment by coblej** [comment]
@dchandekstark Okay.

**Comment by dchandekstark** [comment]
Superseded by #360.

**Comment by jt112** [comment]
As a repository manager, I need to be able to provide the deposit agreement associated with an item.  There is not a 1:1 relationship between agreements and objects and agreements will likely be versioned.  In DSpace, a copy of the deposit agreement the depositor clicks through is saved as a non-public bitstream with the object.

**Comment by dchandekstark** [comment]
Moved to Jira
