### ISSUE TITLE
revise fields extracted from finding aid XML

### ISSUE THREAD

**Issue by seanaery** [duke-libraries/ddr-models#402]
Following UI review/discussion, especially with Noah and DCIT, there are a few revisions desired for what data is extracted from finding aid XML for display in ddr-public. 

The current `titleproper` element (begins "Guide to the...") is the title of the finding aid itself and is less desirable for display than the title of the archival collection. There are also a few other fields that would be valuable to be able to display in the ddr-public UI (e.g., as mouseover info on sidebar link to finding aid, or rendered in full on collection show page, etc.)

So in `lib/ddr/models/finding_aid.rb` could we do the following?

- Collection Title: `//archdesc/did/unittitle`
- Finding Aid URL: `//eadheader/eadid/@url`
- Collection Date Span: `//archdesc/did/unitdate[@type=”inclusive”]`
- Collection Number: `//archdesc/did/unitid`
- Repository: `//archdesc/did/repository/corpname`
- Extent: `//archdesc/did/physdesc/extent`
- Absract (if possible): `//archdesc/did/abstract`

Abstract is typically 5-6 sentences in length, but could be longer.

CC @corylown

**Comment by dchandekstark** [comment]
Would it be a good idea to qualify `//archdesc` as `//archdesc[@level = "collection"]` ?

/cc @noahgh221

**Comment by dchandekstark** [comment]
In the Duke & Sons FA, there are two extents:

```xml
<physdesc altrender="whole">
  <extent altrender="materialtype spaceoccupied">6.5 Linear Feet</extent>
</physdesc>
<physdesc id="aspace_02c35780dfbfe735af687013e2fe0ab6">
  <extent>4000 Items</extent>
</physdesc>
```

Which one do we want? Or both?

/cc @noahgh221

**Comment by dchandekstark** [comment]
You can point to the branch `402-finding-aid-fields` to test new methods on `FindingAid`:

    collection_title
    collection_number
    collection_date_span
    extent
    abstract
    repository

The `title` and `url` methods have not changed.

**Comment by noahgh221** [comment]
David,

Yes, we should qualify //archdesc[@level='collection']

For multiple extent statements, it'd be good to get both.  You could display as: 6.5 Linear Feet (4,000 items).  If that proves too difficult, just take the first one.

**Comment by seanaery** [comment]
@dchandekstark @noahgh221 I'd recommend getting all extents if possible. The 4,000 items one can especially help researchers understand at-a-glance what portion of the archival collection has been digitized / is represented by the digital collection, and we know that to be an important use case.

Imagine, e.g., a "More Like This" section below our item page that includes this info, or a mouseover bubble on the sidebar finding aid link that shows it. 

@noahgh221 Is there any EAD XML attribute for `<extent>` that signals that an item count is an item count (vs. e.g., a linear feet count)? Or is it just generic?

**Comment by noahgh221** [comment]
@seanaery There is a "type" attribute of extent that can qualify the type of extent (linear feet vs. item vs. boxes, etc.)  

http://www.loc.gov/ead/tglib/elements/extent.html

However, ASpace doesn't make use of that attribute in its EAD export mapping.  Instead it uses an "altrender" attribute with some funky stuff.  Here is an example:

<physdesc altrender="whole">
      <extent altrender="materialtype spaceoccupied">0.8  Linear Feet</extent>
      <extent altrender="carrier">456 items</extent>
    </physdesc>


In general, our extent data is inconsistent.  I'd say we only provide item counts 40-50% of the time.  The linear feet count will almost always be present.  If they exist, item counts will probably appear like:
<physdesc altrender="whole">
      <extent altrender="materialtype spaceoccupied">0.8  Linear Feet</extent>
      <extent altrender="carrier">456 items</extent>
    </physdesc>

There may be extent statements that are NOT item counts in the second extent statement as well.  In addition, a given collection may have two separate physdesc elements like:

   <physdesc altrender="whole">
      <extent altrender="materialtype spaceoccupied">0.8  Linear Feet</extent>
      <extent altrender="carrier">3 boxes, 2 volumes</extent>
    </physdesc>
    <physdesc altrender="part">
      <extent altrender="materialtype spaceoccupied">456 GB</extent>
    </physdesc>

So, I'd propose just grabbing the text nodes of everything in the first physdesc and somehow concatenating them.  So, in the above example: 0.8 Linear Feet (3 boxes, 2 volumes).

I think this is what we do in the finding aid display already.

**Comment by dchandekstark** [comment]
Thanks, @noahgh221. If there is an XSLT stylesheet that I could use as a guide, that might be useful. Otherwise, I would propose keeping the logic simple for this use case -- i.e., to concatenate all the text nodes with semicolon + space: `0.8 liner feet; 3 boxes, 2 volumes`. Unless there are more specific directions, it seems hard to know what to put in parens as in your example. How does that sound?

**Comment by noahgh221** [comment]
@dchandekstark Using the semicolon works for me.
