### ISSUE TITLE
Need way to get Fedora version

### ISSUE THREAD

**Issue by coblej** [duke-libraries/ddr-models#406]
previously used AF::Base.connection_for_pid

**Comment by dchandekstark** [comment]
There is not yet a Fedora 4 API for this information.

**Comment by dchandekstark** [comment]
https://jira.duraspace.org/browse/FCREPO-1774

**Comment by dchandekstark** [comment]
@coblej Are we giving up on this?

**Comment by coblej** [comment]
@dchandekstark It's still an open issue in FCREPO Jira, though it's low priority and no one is assigned to it.  I don't care whether we keep this issue open for ourselves or not.
