### ISSUE TITLE
Do we still need move first identifier to local_id?

### ISSUE THREAD

**Issue by coblej** [duke-libraries/ddr-models#407]

**Comment by coblej** [comment]
@dchandekstark I'm inclined to remove Ddr::Models::Base#move_first_identifier_to_local_id from the fcrepo4 branch unless you think there's a reason to keep it.

**Comment by dchandekstark** [comment]
nuke it

**Comment by coblej** [comment]
Addressed by aac8ff07e935a4db3a3c08f5f3ebb6d81e00f7c7
