### ISSUE TITLE
Represent and store the ArchivesSpace identifier for an item in its record.

### ISSUE THREAD

**Issue by willsexton** [duke-libraries/ddr-models#455]
Every component (as in EAD component) in a finding aid generated by ArchivesSpace is assigned a unique identifier, which is used in our UI for linking to that point in the document. Example: http://library.duke.edu/rubenstein/findingaids/rushbenjaminandjulia/#aspace_dccea43034e1b8261e14cf999e86449d

We want to represent that identifier in the item record so we can link to it from the Tripod3 interface. I will work on including it in the METS file for an object, in the sourceMD subsection of the adminSec. See: https://www.loc.gov/standards/mets/docs/mets.v1-9.html#sourceMD 

Since the identifier is specific to ArchivesSpace, it probably makes sense to use a predicate based on this association, like "asid" or something similar. It doesn't seem like ArchivesSpace has an associated ontology at this point.

**Comment by dchandekstark** [comment]
To clarify, you want to store the full URI or just the ID?  Given that we already store the EAD ID and extract the finding aid URL from the EAD doc, we can construct the full URL at runtime.
