### ISSUE TITLE
Version objects when created/updated

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/ddr-models#533]
Copied from duke-libraries/dul-hydra#1589.

**Comment by dchandekstark** [comment]
@coblej I think it could be useful to be able to bypass versioning in certain cases.  If you agree, one way to do it is to pass a new `version: false` option (default: `true`) to `save`.  We would have to override `ActiveFedora::Persistence#create_or_update`.

**Comment by coblej** [comment]
@dchandekstark Okay with me.
