### ISSUE TITLE
DdrUtils.pid_for_identifier throws error if retrieved object does not respond to .parent

### ISSUE THREAD

**Issue by coblej** [duke-libraries/ddr-models#573]
https://github.com/duke-libraries/ddr-models/blob/develop/lib/ddr/utils.rb#L104

NoMethodError: undefined method `parent' for #<Target:0x007f8786111628>
	from /Users/coblej/.rvm/gems/ruby-2.1.5@dul-hydra-f4/gems/activemodel-4.1.14/lib/active_model/attribute_methods.rb:435:in `method_missing'
	from /Users/coblej/.rvm/gems/ruby-2.1.5@dul-hydra-f4/gems/ddr-models-3.0.0.beta.13/lib/ddr/utils.rb:104:in `block in pid_for_identifier'
	from /Users/coblej/.rvm/gems/ruby-2.1.5@dul-hydra-f4/gems/ddr-models-3.0.0.beta.13/lib/ddr/utils.rb:103:in `each'
	from /Users/coblej/.rvm/gems/ruby-2.1.5@dul-hydra-f4/gems/ddr-models-3.0.0.beta.13/lib/ddr/utils.rb:103:in `pid_for_identifier'

**Comment by dchandekstark** [comment]
@coblej Wontfix since #593 ?

**Comment by coblej** [comment]
@dchandekstark Correct.  Closing it.
