### ISSUE TITLE
Add pid_for_local_id method to Ddr::Utils

### ISSUE THREAD

**Issue by coblej** [duke-libraries/ddr-models#581]
It should provide much the same functionality as pid_for_identifier but only look at local_id, not all identifiers.

**Comment by coblej** [comment]
This should probably be handled through a refactoring of the pid_for_identifier method.

**Comment by dchandekstark** [comment]
I think all you need to do is something like:

`.where(Ddr::Index::Fields::LOCAL_ID => local_id).first`

**Comment by coblej** [comment]
@dchandekstark The clause you propose is probably part of the solution but, since local ID's are not unique, this `where` clause often needs to be combined with a model assertion (typically, model is Collection or Item).

**Comment by dchandekstark** [comment]
@coblej If you add as a class method, say, to Ddr::Models::Base, then the model assertion would happen.  E.g.,

```ruby
def self.find_by_local_id! # I like this name better
  results = where(Ddr::Index::Fields::LOCAL_ID => local_id).to_a
  if results.size > 1
    # raise error
  end
  results.first
end
```

**Comment by dchandekstark** [comment]
@coblej Stealing this from you because have #573.

**Comment by coblej** [comment]
@dchandekstark That's fine.  For it to be useful for the purpose I need it for, it should take an optional 'collection' parameter, which, if provided, restricts the search to Items (not Components) in that collection and to the Collection object itself (the local_id might be for the collection itself.

**Comment by coblej** [comment]
@dchandekstark Actually, let's talk about this before you do it.  I want to rethink the best way to accomplish the need that generated this issue.  (Or, if you want to go ahead and do it as you outlined above, it would be more useful for my needs if it didn't throw an exception when the results set was greater than 1 but rather returned them all, permitting further winnowing by the caller.)

I also want to look at how Ddr::Utils.pid_for_identifier is used because I'd like to get rid of that method altogether ... it's an ugly piece of code (and I can say that because I wrote it).

**Comment by dchandekstark** [comment]
@coble OK. I think we should look at using scopes.

**Comment by dchandekstark** [comment]
@coblej Since I've started work on this, maybe I'll just push a PR when ready and we cna continue the conversation over that.  My intention is to get rid of `Ddr::Utils.pid_for_identifier` (or at least deprecate it).

**Comment by coblej** [comment]
@dchandekstark That's fine.  One of the things I want to do today is research where and how `Ddr::Utils.pid_for_identifier` is actually used.

**Comment by dchandekstark** [comment]
@coblej Migrate to JIRA?

**Comment by coblej** [comment]
@dchandekstark I'd say just close it.  Hasn't been done for the past year.  Doesn't seem likely it's going to get done.
