### ISSUE TITLE
Don't auto-generate thumbnails for PDFs

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/ddr-models#6]

**Comment by coblej** [comment]
@dchandekstark In the `fcrepo4` branch, thumbnails are generated only for images, so this issue is addressed there.  So, you can close this ticket unless you want to back-port this change to ddr-models 2.

**Comment by coblej** [comment]
@dchandekstark I decided to take this from you and back-port what I did in fcrepo4 branch so we can use it prior to F4.
