### ISSUE TITLE
Updates should not be allowed for 'locked' objects

### ISSUE THREAD

**Issue by coblej** [duke-libraries/ddr-models#606]
Need to clarify exactly what permissions / abilities are denied for 'locked' objects.  I also assume the restrictions should not apply to superusers.

**Comment by dchandekstark** [comment]
I would say:

cannot :add_children, :update, :replace, :arrange, :publish, :unpublish, :grant

This wont' affect superusers b/c can't trump "can :all" with a "cannot" rule.
