### ISSUE TITLE
Parsing of EDTF encoded dates for year_facet_iim field

### ISSUE THREAD

**Issue by corylown** [duke-libraries/ddr-models#615]
I think the date parsing code (https://github.com/duke-libraries/ddr-models/blob/develop/lib/ddr/models/year_facet.rb) for the year_facet_iim field may need to be updated to support some EDTF encoded dates. For example, dates like "193u/196u" -- the EDTF encoding of "1930s to 1960s" -- don't appear to be parsed correctly. See https://ddr.lib.duke.edu/items/duke:43031 for an example item with this date encoding.

The EDTF Ruby Gem (https://github.com/inukshuk/edtf-ruby) can parse EDTF date strings.

List of EDTF encodings we're using:

EDTF-formatted | example | meaning
--- | --- | ---
yyyy-mm-dd | 2010-12-10 | day precision
yyyy-mm | 2010-12 | month precision
yyyy | 2010 | year precision
yyyy/yyyy | 1999/2001 | interval with year precision; 1999 to 2001
yyyy-mm/yyyy-mm | 2010-11/2010-12 | interval with month precision
yyyy-mm-dd/yyyy-mm-dd | 2010-12-10/2010-12-20 | interval with day precision
[yyyy,yyyy,yyyy] | [1999,2000,2003] | one of a set; 1999, 2000 or 2003
yyyy~ | 2010~ | approximate date with year precision; circa 2010
yyyy~/yyyy~ | 1999~/2001~ | approximate interval with year precision; circa 1999 to 2001
yyyy?/yyyy? | 1999?/2001? | uncertain interval with year precision; 1999? to 2001?
yyyu/yyyu | 199u/200u | interval with unspecified year; 1990s to 2000s
yyyx | 199x | date with decade precision; 1990s
yyxx | 19xx | date with century precision; 1900s
yyyu | 199u | date with unspecified year; 199x
yyuu | 19uu | date with unspecified decade; 19xx
yyyy-mm-dd? | 2010-12-10? | uncertain date with day precision
yyyy-mm? | 2010-12? | uncertain date with month precision
yyyy? | 2010? | uncertain date with year precision
yyyy-21 | 2010-21 | Spring 2010
yyyy-22 | 2010-22 | Summer 2010
yyyy-23 | 2010-23 | Fall 2010
yyyy-24 | 2010-24 | Winter 2010

**Comment by dchandekstark** [comment]
@corylown Note that "x" and "u" are quite different in EDTF:

```
>> d = EDTF.parse("19uu")
 => Mon, 01 Jan 1900 
>> d.class
 => Date 
>> d = EDTF.parse("19xx")
 => #<EDTF::Century:0x007fc991f02ed8 @year=1900> 
>> d.map(&:year)
 => [1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999] 
```

**Comment by dchandekstark** [comment]
@corylown I think I've clarified this with @maggiedickson.

**Comment by dchandekstark** [comment]
@corylown You might want to look at #619 to check that the coverage is complete and correct.

**Comment by corylown** [comment]
@dchandekstark thanks! I'm at Solr training today, but will take a look later this afternoon.

**Comment by dchandekstark** [comment]
@corylown OK, @coblej already merged it, so we can patch anything that's wrong or missing. I explained to @maggiedickson yesterday that I had to munge the usage of "u" b/c edtf-ruby doesn't produce the kind of range we need for this facet.

**Comment by corylown** [comment]
&#x1f44d; @dchandekstark the changes made in #619 look good to me. I tried it with all the variations of EDTF that I know we're using and it works as expected.
