### ISSUE TITLE
Ddr::Auth::WebAuthContext includes ismemberof and affiliation even when anonymous

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/ddr-models#641]
This is not a security issue, but causes some confusion b/c user who has an SSO context may be granted privileges (appropriately) even though they are not logged in to the app.

I believe the desired or expected behavior would be to override `super` in `affiliation` and `ismemberof` only when `!anonymous?`.

/cc @coblej @corylown @seanaery

**Comment by coblej** [comment]
@corylown @seanaery ddr-models v3.0.2 has been released and includes the fix in this pull request that addresses an issue I believe you had with the public UI where a SSO user's auth context was being used in access controls even though the user was not logged into the public UI app itself.
